import {
  Airplane,
  Bus,
  Car,
  ForkKnife,
  Leaf,
  Lightning,
  Train,
} from "phosphor-react-native";
import { colors } from "./theme";

export const cfpCategories = [
  {
    label: "Car Travel (Petrol)",
    value: "car_petrol",
    factor: 0.192,
    unit: "km",
    icon: Car,
    color: colors.rose,
  },
  {
    label: "Car Travel (Diesel)",
    value: "car_diesel",
    factor: 0.171,
    unit: "km",
    icon: Car,
    color: colors.rose,
  },
  {
    label: "Bus",
    value: "bus",
    factor: 0.105,
    unit: "km",
    icon: Bus,
    color: colors.primaryDark,
  },
  {
    label: "Train",
    value: "train",
    factor: 0.041,
    unit: "km",
    icon: Train,
    color: colors.primaryDark,
  },
  {
    label: "Flight (Short Haul)",
    value: "flight_short",
    factor: 0.255,
    unit: "km",
    icon: Airplane,
    color: colors.rose,
  },
  {
    label: "Beef",
    value: "beef",
    factor: 27.0,
    unit: "kg",
    icon: ForkKnife,
    color: colors.rose,
  },
  {
    label: "Chicken",
    value: "chicken",
    factor: 6.9,
    unit: "kg",
    icon: ForkKnife,
    color: colors.rose,
  },
  {
    label: "Vegetarian Meal",
    value: "veg_meal",
    factor: 2.0,
    unit: "serving",
    icon: Leaf,
    color: colors.green,
  },
  {
    label: "Electricity",
    value: "electricity",
    factor: 0.5,
    unit: "kWh",
    icon: Lightning,
    color: "#eab308",
  },
];
